version: "3.8"

services:
  routes_service:
    build: ./routes-service/
    env_file:
      - routes-service/.env
    ports:
      - "4050:8000"
    depends_on:
      - auth_service

  auth_service:
    build: ./auth-service/
    env_file:
      - auth-service/.env
    ports:
      - "4051:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB} 
        PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - routes-service/.env
    ports:
      - 5433:5432

volumes:
    postgres_data: